version: '3.8'

services:
  server:
    build: "./backend"
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - "./backend:/home/node/app"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://ayush:ayushKaSecret@db:27017/messaging-app
      - JWT_SECRET=yemerasecrethaibrotuapnabanale
      - FRONTEND_URL=http://localhost:3000

  client:
    build: "./frontend"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    
  db:
    image: mongo:7.0-jammy
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
